### ISSUE TITLE
生物收集器错误收集物品bug

### ISSUE THREAD

**Issue by MonkeyProgrammer1** [SlimefunGuguProject/Supreme#11]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述

在荧光鱿鱼旁边放生物收集器，在机器里面放玻璃瓶，收集后得到的是墨囊
**本地服测试为3级机器出现问题，但之前为1级机器出问题**

### 复现步骤

1.在荧光鱿鱼旁边放生物收集器
2.在机器放入玻璃瓶

### 预期行为

应该收集为发光墨囊

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

v2022.07-release

### 插件版本

5

**Comment by ybw0014** [comment]
请尝试新版本是否仍有该问题

**Comment by MonkeyProgrammer1** [comment]
问题仍然存在，并再次测试时出现在生物收集器3、2，在重启服务器后出现在任意版本的生物收集器

**Comment by MonkeyProgrammer1** [comment]
问题仍然存在，并再次测试时出现在生物收集器3、2，在重启服务器后出现在任意版本的生物收集器

**Comment by ybw0014** [comment]
尝试新版本

**Comment by MonkeyProgrammer1** [comment]
问题仍然存在

**Comment by ybw0014** [comment]
那就得魔改了，稍等

**Comment by MonkeyProgrammer1** [comment]
该问题已解决
