### ISSUE TITLE
科技机器人无法升级机械蜜蜂,机械铁傀儡,机械僵尸

### ISSUE THREAD

**Issue by shixinzia** [SlimefunGuguProject/Supreme#12]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [x] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述

科技机器人输入输出错误,1组同等级机器人只能获取1个同等级机器人

### 复现步骤

1.准备科技机器人任意等级,和1组1级蜜蜂
2.蜜蜂丢入科技机器人,接电
3.1组1级蜜蜂消失,产出一个1级蜜蜂

### 预期行为

应该出现更高级的蜜蜂

### 服务器日志

无

### 错误报告

五

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

v4.9 b416562-canary

### 插件版本

5

**Comment by MonkeyProgrammer1** [comment]
该问题经测试存在，并存在于任意等级蜜蜂升级后出现一级蜜蜂

**Comment by shixinzia** [comment]
问题仍旧存在

**Comment by shixinzia** [comment]
目前构建版本8,问题还是存在

**Comment by Violet-Nonbloosom** [comment]
我这边没能成功复现。

我用的是 Spigot，1.18.2 。

Slimefun 版本是 2022.08-release 。

Supreme 版本是构建版本 8。
