### ISSUE TITLE
部分机器的功率单位不正确

### ISSUE THREAD

**Issue by Violet-Nonbloosom** [SlimefunGuguProject/Supreme#15]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述
部分机器的功率单位不正确。

具体来说，大部分机器的功率单位都标注为 **J/s**，但它们的实际功率明显是 **J/tick**，其中 tick 表示粘液刻。

这导致所有按时间计算功率的机器功率是标注功率的两倍。

之前我在官方版下发了一条 [issue](https://github.com/RelativoBR/Supreme/issues/16) 提交这个漏洞，目前没有回应。

---

另外，我在官方版下发的 issue，使用了另外的配置，与汉化版无关。

### 复现步骤

1. 在同一个网络中，放置 1 个能源调节器，5 个太阳能发电机（共计 20 W）和1 个一级电芯机；
2. 在电芯机里放入一个圆石，可以观察到电芯机**断断续续地**工作；
3. 再放 5 个太阳能发电机（加上之前的发电机，合计 40 W），可以观察到电芯机**正常**工作。

我在官方版下发 issue 时，使用的就是上面的例子。

### 预期行为

- 调整功率的标注，使其与实际情况相符；
- 调整所有实际功率，使其匹配标注。

二者选其一。
不过，如果采用第二个方案，生物科技也得跟着调整，还挺麻烦的。

### 服务端软件

Spigot

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![图片](https://user-images.githubusercontent.com/86547296/194333707-4b982d28-cc2b-48b1-b893-5f117079da8e.png)

我在官方版下方发 issue 时，使用的是**另一张**图，**切勿混淆**。

### 插件版本

9

**Comment by ybw0014** [comment]
多个问题请分开汇报

**Comment by Violet-Nonbloosom** [comment]
已将原有的汇报分拆完成。
