### ISSUE TITLE
手册查看结晶零件报错

### ISSUE THREAD

**Issue by Phi-2X** [SlimefunGuguProject/Supreme#34]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Supreme/issues)，且没有找到相同的问题

### 问题描述

结晶零件在手册中无法查看合成表，产生如下报错后手册无法再打开，退出重进后手册可打开但问题复现。
目前就结晶零件不能打开(又来一个)

### 复现步骤

1.使用paper-1.21-117开服并安装slimefun,guizhanlib,supreme插件
2.打开手册查看结晶零件

### 预期行为

能查看结晶零件合成表

### 服务器日志

https://paste.guizhanss.net/xflW9

### 服务端软件

Paper

### Minecraft 版本

1.21

### Slimefun版本

![image](https://github.com/user-attachments/assets/fcb7f0d3-4c51-4cba-a0d3-9d7908063e9e)

### 插件版本

Build 21 (git 77e2274)

**Comment by ybw0014** [comment]
Supreme真是太棒辣
